
from dnnutil import phonestashwithoutnoise as phonestash

import os

phone_stash = phonestash.phone_stash

en_corpus = "/en_uk_all_kids_aligned_with_clean-d/" #en_uk_kids_align_from_clean-2"
en_pickle_dir='../features/work_in_progress/'+en_corpus+'/pickles'

#en_atr_corpus = 'en_uk_atr_kids_kaldi-align-2'
#en_atr_pickle_dir='../features/work_in_progress/'+en_atr_corpus+'/pickles'


fi_corpus = "speecon_kids_kaldi_align"
fi_pickle_dir='../features/work_in_progress/'+fi_corpus+'/pickles'

test_corpus = "more_fysiak-gamedata-2-aligned_with_mc_b" #"fysiak-gamedata-2"
test_pickle_dir='../features/work_in_progress/'+test_corpus+'/pickles'

if 1 == 2:
    print ("PF-Star train")
    traindata = phone_stash([  os.path.join(en_pickle_dir, 'test_017f10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_022m11bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_023m11nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_026f10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_032m11nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_040f07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_040f09nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_041f07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_041f08nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_041f09nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_041m06nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_042f07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_042f08nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_042m06nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_043f07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_043f09nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_043m06bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_043m07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_044m06nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_044m07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_045f07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_045m06nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_045m08nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_054m06nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_082f07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_083m07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_120f06nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_120m06nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_123f07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_162f09sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_166f09sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_168f09sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_174m09sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_177f09sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_178m09sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_180f09sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_187f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_188f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_189f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_195m08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'test_197m08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_001f12bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_001m14bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_002f12bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_002m14bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_003m13bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_004f05bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_004m04bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_004m13bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_005m10bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_005m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_005m14bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_006m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_007f13bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_007m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_016f10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_019f10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_020m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_020m12bh_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_021f11nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_024m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_025m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_027m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_028m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_029m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_030m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_031f10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_033m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_034m11nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_035m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_036f10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_037f11nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_038m11nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_039f11nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_042f06nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_042m10nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_081m06nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_082f06nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_083f07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_084m07nl_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_161m10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_163f10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_164m10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_165m10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_167m10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_169f10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_170m10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_171m10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_172f10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_173m10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_175m10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_176m10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_179m09sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_181f10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_182f09sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_183f10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_185f10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_186m10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_190f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_191f07sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_192f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_193f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_194f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_196f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_198f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_199m08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_200f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_201m08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_202f07sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_203f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_204m08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_205m08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_206f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_207f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_208f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_210f08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_211m08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_212m08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_213m08sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_216m10sp_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'train_248f08sp_melbin26_and_f0_alldata.pickle2')] )

    print ("ATR-kids train")
    atr_data = phone_stash([ os.path.join(en_pickle_dir, 'wavfiles_Participant10-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant11-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant12-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant13-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant14a-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant14b-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant14c-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant15-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant16-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant17-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant18-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant19-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant1-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant20-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant21-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant22-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant23-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant24-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant25-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant26-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant27-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant28-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant29-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant2-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant30-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant31-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant32-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant33a-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant33b-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant34-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant35-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant36-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant37-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant38-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant39-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant3-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant40-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant41-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant42-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant43-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant44-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant4-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant5-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant6-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant7-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant8-_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(en_pickle_dir, 'wavfiles_Participant9-_melbin26_and_f0_alldata.pickle2')])
    print ("Speecon-kids train")
    speecontrain_data = phone_stash([ os.path.join(fi_pickle_dir, '001.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '002.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '003.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '004.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '005.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '006.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '007.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '008.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '009.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '010.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '011.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '012.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '013.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '014.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '015.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '016.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '017.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '018.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '019.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '020.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '021.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '022.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '023.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '024.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '025.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '026.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '027.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '028.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '029.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '030.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '031.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '032.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '033.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '034.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '035.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '036.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '037.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '038.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '039.recipe_melbin26_and_f0_alldata.pickle2'),
                               os.path.join(fi_pickle_dir, '040.recipe_melbin26_and_f0_alldata.pickle2'),
                          ])
    

    print ("PF-Star devel")
    eval_uk_data = phone_stash([ os.path.join(en_pickle_dir, 'test_001m10nl_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_002m10nl_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_003m10bh_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_003m10nl_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_004f06bh_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_004f11nl_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_004m08bh_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_004m10bh_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_005f06bh_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_005m08bh_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_006f10bh_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_008m11nl_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_009f11nl_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_010m11nl_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_011f10nl_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_012f11nl_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_013f11nl_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_014f11nl_melbin26_and_f0_alldata.pickle2'),
                                 os.path.join(en_pickle_dir, 'test_015f10nl_melbin26_and_f0_alldata.pickle2')                                                          
                             ], zmean=traindata.mean, zstd=traindata.std, max_len=traindata.max_len)
    
    print ("Speecon-kids devel")
    eval_fi_data = phone_stash([  os.path.join(fi_pickle_dir, '041.recipe_melbin26_and_f0_alldata.pickle2'),
                             os.path.join(fi_pickle_dir, '042.recipe_melbin26_and_f0_alldata.pickle2'),
                             os.path.join(fi_pickle_dir, '043.recipe_melbin26_and_f0_alldata.pickle2'),
                             os.path.join(fi_pickle_dir, '044.recipe_melbin26_and_f0_alldata.pickle2'),
                             os.path.join(fi_pickle_dir, '045.recipe_melbin26_and_f0_alldata.pickle2'),
                             os.path.join(fi_pickle_dir, '046.recipe_melbin26_and_f0_alldata.pickle2'),
                             os.path.join(fi_pickle_dir, '047.recipe_melbin26_and_f0_alldata.pickle2'),
                             os.path.join(fi_pickle_dir, '048.recipe_melbin26_and_f0_alldata.pickle2'),
                             os.path.join(fi_pickle_dir, '049.recipe_melbin26_and_f0_alldata.pickle2'),
                             os.path.join(fi_pickle_dir, '050.recipe_melbin26_and_f0_alldata.pickle2')
                         ], zmean=traindata.mean, zstd=traindata.std, max_len=traindata.max_len)
if 1 == 1:
    players_bad_data = phone_stash([ os.path.join(test_pickle_dir, 'disqualified-mc_b_melbin36_and_f0_alldata.pickle2'),
                             ]) #, zmean=traindata.mean, zstd=traindata.std, max_len=traindata.max_len)

    players_ok_data = phone_stash([ os.path.join(test_pickle_dir, 'some_stars-mc_b_melbin36_and_f0_alldata.pickle2'),
                            ])#, zmean=traindata.mean, zstd=traindata.std, max_len=traindata.max_len)

    players_good_data =  phone_stash([ os.path.join(test_pickle_dir, 'lots_of_stars-mc_b_melbin36_and_f0_alldata.pickle2'),
                               ])#, zmean=traindata.mean, zstd=traindata.std, max_len=traindata.max_len)


    players_native_data =  phone_stash([ os.path.join(test_pickle_dir, 'native_or_nativelike-mc_b_melbin36_and_f0_alldata.pickle2'),
                                 ])#, zmean=traindata.mean, zstd=traindata.std, max_len=traindata.max_len)
